const { GoogleGenerativeAI } = require("@google/generative-ai");

// Fetch the API Key from env variables
const apiKey = process.env.GEMINI_API_KEY;

let model = null;

if (apiKey && apiKey !== "your_gemini_api_key") {
  try {
    // Initialize the official Google Generative AI SDK
    const genAI = new GoogleGenerativeAI(apiKey);
    // Use the latest, high-speed 'gemini-1.5-flash' model
    model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
    console.log("Gemini AI Client initialized successfully.");
  } catch (error) {
    console.error("Failed to initialize Gemini AI Client:", error.message);
  }
} else {
  console.warn("GEMINI_API_KEY is not configured in .env. Running Gemini in Mock Fallback Mode.");
}

/**
 * Generate content using Google Gemini API
 * Supports text prompt and returns clean generated text
 */
const generateContent = async (prompt) => {
  // Mock Fallback Mode for developer ease
  if (!model) {
    console.log("Mocking Gemini AI generation (no GEMINI_API_KEY found)");
    return getMockResponseForPrompt(prompt);
  }

  try {
    const result = await model.generateContent(prompt);
    const response = await result.response;
    return response.text();
  } catch (error) {
    console.error("Gemini API execution error:", error.message);
    throw new Error(`Gemini API Error: ${error.message}`);
  }
};

/**
 * Provides helpful mock fallback responses so developers can test feature flows without keys
 */
const getMockResponseForPrompt = (prompt) => {
  const lowerPrompt = prompt.toLowerCase();
  
  if (lowerPrompt.includes("breakdown") || lowerPrompt.includes("subtasks")) {
    return JSON.stringify({
      subtasks: [
        { title: "Define Requirements and Scope", description: "List all core requirements and project boundaries." },
        { title: "Draft Technical Design Document", description: "Design database schemas, endpoints, and architectural diagrams." },
        { title: "Setup Project Boilerplate", description: "Initialize repository, dependencies, and linting standards." },
        { title: "Build Database Layer", description: "Implement schemas, models, and migrations." },
        { title: "Write API Integration Tests", description: "Validate route controls and input schema parsing." }
      ]
    }, null, 2);
  }

  if (lowerPrompt.includes("priority") || lowerPrompt.includes("detect")) {
    return JSON.stringify({
      suggestedPriority: "high",
      reasoning: "The task contains urgent terminology ('ASAP', 'immediately') and targets core billing infrastructure, presenting significant operational risk."
    }, null, 2);
  }

  if (lowerPrompt.includes("roadmap") || lowerPrompt.includes("milestone")) {
    return JSON.stringify({
      phases: [
        {
          phase: "Phase 1: Foundation & Specs",
          timeline: "Weeks 1-2",
          items: ["Finalize requirements", "Setup local development DB", "Configure basic authorization middleware"]
        },
        {
          phase: "Phase 2: Core Engineering",
          timeline: "Weeks 3-5",
          items: ["Build task management schemas", "Implement multi-tenant plugin hook", "Hook Socket.IO notifications"]
        },
        {
          phase: "Phase 3: QA & Deployment",
          timeline: "Week 6",
          items: ["Perform integration testing", "Configure staging environment", "Promote production bundle"]
        }
      ]
    }, null, 2);
  }

  return "This is a clean, automated summary of the task details generated by the TaskFlow AI assistant.";
};

module.exports = {
  generateContent,
  isAiConfigured: () => !!model,
};
